# Generated by Django 4.2.4 on 2023-08-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='id_checklist',
        ),
    ]
